apiVersion: apps/v1
kind: Deployment
metadata:
  name: "goserver"
  labels:
    app: "goserver"
spec:
  replicas: 10
  selector:
    matchLabels:
      app: "goserver"
  template:
    metadata:
      labels:
        app: "goserver"
    spec:
      containers:
      - name: "goserver"
        image: "guilhermeassuncao/hello-go:v3"
        envFrom:
          - configMapRef:
              name: goserver-env

        # env:
        # - name: "NAME"
        #   valueFrom:
        #     configMapKeyRef:
        #       name: goserver-env
        #       key: NAME
        # - name: "AGE"
        #   valueFrom:
        #     configMapKeyRef:
        #       name: goserver-env
        #       key: AGE